version: '2'
services:
  app:
    build: .
    restart: always
    environment:
      VIRTUAL_HOST: ceremony.tornado.cash
      LETSENCRYPT_HOST: ceremony.tornado.cash
      nginx_client_max_body_size: 50m
      nginx_proxy_read_timeout: 600s
      MYSQL_HOST: mysql
    env_file: .env.production
    volumes:
      - app:/app/server/snark_files
    # depends_on:
    #   - mysql
    ports:
      - 3000:80
    command: "yarn start"

  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7.19
    restart: always
    # env_file: .env.production
    # ports:
    #   - 3306:33306
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_HOST: '172.*.*.*'
      MYSQL_DATABASE: phase2
      MYSQL_ROOT_PASSWORD: master
    volumes:
      - mysql:/var/lib/mysql
      # - mysqld.cnf:/etc/my.cnf

volumes:
  app:
  mysql:

networks:
  default:
    external:
      name: frontend_default
